CLASS_NAMES = [
    {'class_code': '-B', 'deskripsi': 'Aksara Murda Ba yang dipangkon', 'aksara': None, 'terjemahan': 'B', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-G', 'deskripsi': 'Aksara Murda Ga yang dipangkon', 'aksara': None, 'terjemahan': 'G', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-K', 'deskripsi': 'Aksara Murda Ka yang dipangkon', 'aksara': None, 'terjemahan': 'K', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-N', 'deskripsi': 'Aksara Murda Na yang dipangkon', 'aksara': None, 'terjemahan': 'N', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-Ny', 'deskripsi': 'Aksara Murda Nya yang dipangkon', 'aksara': None, 'terjemahan': 'Ny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-P', 'deskripsi': 'Aksara Murda Pa yang dipangkon', 'aksara': None, 'terjemahan': 'P', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-S', 'deskripsi': 'Aksara Murda Sa yang dipangkon', 'aksara': None, 'terjemahan': 'S', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-T', 'deskripsi': 'Aksara Murda Ta yang dipangkon', 'aksara': None, 'terjemahan': 'T', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-b', 'deskripsi': 'Aksara Carakan ba yang dipangkon', 'aksara': None, 'terjemahan': 'b', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-c', 'deskripsi': 'Aksara Carakan ca yang dipangkon', 'aksara': None, 'terjemahan': 'c', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-d', 'deskripsi': 'Aksara Carakan da yang dipangkon', 'aksara': None, 'terjemahan': 'd', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-dh', 'deskripsi': 'Aksara Carakan dha yang dipangkon', 'aksara': None, 'terjemahan': 'dh', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-g', 'deskripsi': 'Aksara Carakan ga yang dipangkon', 'aksara': None, 'terjemahan': 'g', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-j', 'deskripsi': 'Aksara Carakan ja yang dipangkon', 'aksara': None, 'terjemahan': 'j', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-k', 'deskripsi': 'Aksara Carakan ka yang dipangkon', 'aksara': None, 'terjemahan': 'k', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-l', 'deskripsi': 'Aksara Carakan la yang dipangkon', 'aksara': None, 'terjemahan': 'l', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-m', 'deskripsi': 'Aksara Carakan ma yang dipangkon', 'aksara': None, 'terjemahan': 'm', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-n', 'deskripsi': 'Aksara Carakan na yang dipangkon', 'aksara': None, 'terjemahan': 'n', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-ny', 'deskripsi': 'Aksara Carakan nya yang dipangkon', 'aksara': None, 'terjemahan': 'ny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-p', 'deskripsi': 'Aksara Carakan pa yang dipangkon', 'aksara': None, 'terjemahan': 'p', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-r', 'deskripsi': 'Aksara Carakan ra yang dipangkon', 'aksara': None, 'terjemahan': 'r', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-s', 'deskripsi': 'Aksara Carakan sa yang dipangkon', 'aksara': None, 'terjemahan': 's', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-t', 'deskripsi': "Aksara Carakan ta yang dipangkon", 'aksara': None, 'terjemahan': 't', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-th', 'deskripsi': "Aksara Carakan tha yang dipangkon", 'aksara': None, 'terjemahan': 'th', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-w', 'deskripsi': "Aksara Carakan wa yang dipangkon", 'aksara': None, 'terjemahan': 'w', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '-y', 'deskripsi': "Aksara Carakan ya yang dipangkon", 'aksara': None, 'terjemahan': 'y', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '0', 'deskripsi': 'Aksara Wilangan 0', 'aksara': None, 'terjemahan': '0', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '4', 'deskripsi': 'Aksara Wilangan 4', 'aksara': None, 'terjemahan': '4', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '5', 'deskripsi': 'Aksara Wilangan 5', 'aksara': None, 'terjemahan': '5', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '6', 'deskripsi': 'Aksara Wilangan 6', 'aksara': None, 'terjemahan': '6', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'A', 'deskripsi': 'Aksara Swara A', 'aksara': None, 'terjemahan': 'A', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'B', 'deskripsi': 'Aksara Murda Ba', 'aksara': None, 'terjemahan': 'B', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Bn', 'deskripsi': 'Aksara Murda Ba dipasangkan aksara na', 'aksara': None, 'terjemahan': 'Bn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Bnu', 'deskripsi': 'Aksara Murda Ba dipasangkan aksara na yang di suku', 'aksara': None, 'terjemahan': 'Bnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Br', 'deskripsi': 'Aksara Murda Ba disandhangkan cakra', 'aksara': None, 'terjemahan': 'Br', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Bre', 'deskripsi': 'Aksara Murda Ba disandhangkan cekre', 'aksara': None, 'terjemahan': 'Bre', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Bru', 'deskripsi': 'Aksara Murda Ba disandhangkan carka + suku', 'aksara': None, 'terjemahan': 'Bru', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Bu', 'deskripsi': 'Aksara Murda Ba disandhangkan suku', 'aksara': None, 'terjemahan': 'Bu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Bw', 'deskripsi': 'Aksara Murda Ba dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'Bw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Bwr', 'deskripsi': 'Aksara Murda Ba dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'Bwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Bwre', 'deskripsi': 'Aksara Murda Ba dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'Bwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Bwru', 'deskripsi': 'Aksara Murda Ba dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Bwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Bwu', 'deskripsi': 'Aksara Murda Ba dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'Bwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'By', 'deskripsi': 'Aksara Murda Ba disandhangkan pengkal', 'aksara': None, 'terjemahan': 'By', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Byu', 'deskripsi': 'Aksara Murda Ba disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'Byu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'E', 'deskripsi': 'Aksara Swara E', 'aksara': None, 'terjemahan': 'E', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'G', 'deskripsi': 'Aksara Murda Ga', 'aksara': None, 'terjemahan': 'G', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Gn', 'deskripsi': 'Aksara Murda Ga dipasangkan aksara na', 'aksara': None, 'terjemahan': 'Gn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Gnu', 'deskripsi': 'Aksara Murda Ga dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'Gnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Gr', 'deskripsi': 'Aksara Murda Ga disandhangkan cakra', 'aksara': None, 'terjemahan': 'Gr', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Gre', 'deskripsi': 'Aksara Murda Ga disandhangkan cekre', 'aksara': None, 'terjemahan': 'Gre', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Gru', 'deskripsi': 'Aksara Murda Ga disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Gru', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Gu', 'deskripsi': 'Aksara Murda Ga disandhangkan suku', 'aksara': None, 'terjemahan': 'Gu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Gw', 'deskripsi': 'Aksara Murda Ga dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'Gw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Gwr', 'deskripsi': 'Aksara Murda Ga dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'Gwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Gwre', 'deskripsi': 'Aksara Murda Ga dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'Gwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Gwru', 'deskripsi': 'Aksara Murda Ga dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Gwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Gwu', 'deskripsi': 'Aksara Murda Ga dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'Gwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Gy', 'deskripsi': 'Aksara Murda Ga disandhangkan pengkal', 'aksara': None, 'terjemahan': 'Gy', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Gyu', 'deskripsi': 'Aksara Murda Ga disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'Gyu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'I', 'deskripsi': 'Aksara Swara I', 'aksara': None, 'terjemahan': 'I', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'K', 'deskripsi': 'Aksara Murda Ka', 'aksara': None, 'terjemahan': 'K', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Kn', 'deskripsi': 'Aksara Murda Ka dipasangkan aksara na', 'aksara': None, 'terjemahan': 'Kn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Knu', 'deskripsi': 'Aksara Murda Ka dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'Knu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Kr', 'deskripsi': 'Aksara Murda Ka disandhangkan cakra', 'aksara': None, 'terjemahan': 'Kr', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Kre', 'deskripsi': 'Aksara Murda Ka disandhangkan cekre', 'aksara': None, 'terjemahan': 'Kre', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Kru', 'deskripsi': 'Aksara Murda Ka disandangkan cakra + suku', 'aksara': None, 'terjemahan': 'Kru', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Ku', 'deskripsi': 'Aksara Murda Ka disandhangkan suku', 'aksara': None, 'terjemahan': 'Ku', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Kw', 'deskripsi': 'Aksara Murda Ka dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'Kw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Kwr', 'deskripsi': 'Aksara Murda Ka dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'Kwr', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Kwre', 'deskripsi': 'Aksara Murda Ka dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'Kwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Kwru', 'deskripsi': 'Aksara Murda Ka dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Kwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Kwu', 'deskripsi': 'Aksara Murda Ka dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'Kwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Ky', 'deskripsi': 'Aksara Murda Ka disandhangkan pengkal', 'aksara': None, 'terjemahan': 'Ky', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Kyu', 'deskripsi': 'Aksara Murda Ka disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'Kyu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'N', 'deskripsi': 'Aksara Murda Na', 'aksara': None, 'terjemahan': 'N', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Nn', 'deskripsi': 'Aksara Murda Na dipasangkan aksara na', 'aksara': None, 'terjemahan': 'Nn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Nnu', 'deskripsi': 'Aksara Murda Na dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'Nnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Nr', 'deskripsi': 'Aksara Murda Na disandhangkan cakra', 'aksara': None, 'terjemahan': 'Nr', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Nre', 'deskripsi': 'Aksara Murda Na disandhangkan cekre', 'aksara': None, 'terjemahan': 'Nre', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Nru', 'deskripsi': 'Aksara Murda Na disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Nru', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Nu', 'deskripsi': 'Aksara Murda Na disandhangkan suku', 'aksara': None, 'terjemahan': 'Nu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Nw', 'deskripsi': 'Aksara Murda Na dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'Nw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Nwr', 'deskripsi': 'Aksara Murda Na dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'Nwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Nwre', 'deskripsi': 'Aksara Murda Na dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'Nwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Nwru', 'deskripsi': 'Aksara Murda Na dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Nwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Nwu', 'deskripsi': 'Aksara Murda Na dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'Nwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Ny', 'deskripsi': 'Aksara Murda Na disandhangkan pengkal', 'aksara': None, 'terjemahan': 'Ny', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Ny1', 'deskripsi': 'Aksara Murda Nya', 'aksara': None, 'terjemahan': 'Ny', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Nyn', 'deskripsi': 'Aksara Murda Nya dipasangkan aksara na', 'aksara': None, 'terjemahan': 'Nyn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Nynu', 'deskripsi': 'Aksara Murda Nya dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'Nynu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Nyr', 'deskripsi': 'Aksara Murda Nya disandhangkan cakra', 'aksara': None, 'terjemahan': 'Nyr', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Nyre', 'deskripsi': 'Aksara Murda Nya disandhangkan cekre', 'aksara': None, 'terjemahan': 'Nyre', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Nyru', 'deskripsi': 'Aksara Murda Nya disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Nyru', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Nyu', 'deskripsi': 'Aksara Murda Na disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'Nyu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Nyu1', 'deskripsi': 'Aksara Murda Nya disandhangkan suku', 'aksara': None, 'terjemahan': 'Nyu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Nyw', 'deskripsi': 'Aksara Murda Nya dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'Nyw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Nywr', 'deskripsi': 'Aksara Murda Nya dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'Nywr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Nywre', 'deskripsi': 'Aksara Murda Nya dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'Nywre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Nywru', 'deskripsi': 'Aksara Murda Nya dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Nywru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Nywu', 'deskripsi': 'Aksara Murda Nya dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'Nywu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Nyy', 'deskripsi': 'Aksara Murda Nya disandhangkan pengkal', 'aksara': None, 'terjemahan': 'Nyy', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Nyyu', 'deskripsi': 'Aksara Murda Nya disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'Nyyu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'O', 'deskripsi': 'Aksara Swara O', 'aksara': None, 'terjemahan': 'O', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'P', 'deskripsi': 'Aksara Murda Pa', 'aksara': None, 'terjemahan': 'P', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Pn', 'deskripsi': 'Aksara Murda Pa dipasangkan aksara na', 'aksara': None, 'terjemahan': 'Pn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Pnu', 'deskripsi': 'Aksara Murda Pa dipasangkan aksara na + suku', 'aksara': None, 'terjemahan': 'Pnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Pr', 'deskripsi': 'Aksara Murda Pa disandhangkan cakra', 'aksara': None, 'terjemahan': 'Pr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Pre', 'deskripsi': 'Aksara Murda Pa disandhangkan cekre', 'aksara': None, 'terjemahan': 'Pre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Pru', 'deskripsi': 'Aksara Murda Pa disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Pru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Pu', 'deskripsi': 'Aksara Murda Pa disandhangkan suku', 'aksara': None, 'terjemahan': 'Pu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Pw', 'deskripsi': 'Aksara Murda Pa dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'Pw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Pwr', 'deskripsi': 'Aksara Murda Pa dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'Pwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Pwre', 'deskripsi': 'Aksara Murda Pa dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'Pwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Pwru', 'deskripsi': 'Aksara Murda Pa disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Pwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Pwu', 'deskripsi': 'Aksara Murda Pa dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'Pwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Py', 'deskripsi': 'Aksara Murda Pa disandhangkan pengkal', 'aksara': None, 'terjemahan': 'Py', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Pyu', 'deskripsi': 'Aksara Murda Pa disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'Pyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'S', 'deskripsi': 'Aksara Murda Sa', 'aksara': None, 'terjemahan': 'S', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Sn', 'deskripsi': 'Aksara Murda Sa dipasangkan aksara na', 'aksara': None, 'terjemahan': 'Sn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Snu', 'deskripsi': 'Aksara Murda Sa dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'Snu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Sr', 'deskripsi': 'Aksara Murda Sa disandhangkan cakra', 'aksara': None, 'terjemahan': 'Sr', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Sre', 'deskripsi': 'Aksara Murda Sa disandhangkan cekre', 'aksara': None, 'terjemahan': 'Sre', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Sru', 'deskripsi': 'Aksara Murda Sa disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Sru', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Su', 'deskripsi': 'Aksara Murda Sa disandhangkan suku', 'aksara': None, 'terjemahan': 'Su', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Sw', 'deskripsi': 'Aksara Murda Sa dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'Sw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Swr', 'deskripsi': 'Aksara Murda Sa dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'Swr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Swre', 'deskripsi': 'Aksara Murda Sa dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'Swre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Swru', 'deskripsi': 'Aksara Murda Sa dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Swru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Swu', 'deskripsi': 'Aksara Murda Sa dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'Swu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Sy', 'deskripsi': 'Aksara Murda Sa disandhangkan pengkal', 'aksara': None, 'terjemahan': 'Sy', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'Syu', 'deskripsi': 'Aksara Murda Sa disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'Syu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'T', 'deskripsi': 'Aksara Murda Ta', 'aksara': None, 'terjemahan': 'T', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Tn', 'deskripsi': 'Aksara Murda Ta dipasangkan aksara na', 'aksara': None, 'terjemahan': 'Tn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Tnu', 'deskripsi': 'Aksara Murda Ta dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'Tnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Tr', 'deskripsi': 'Aksara Murda Ta disandhangkan cakra', 'aksara': None, 'terjemahan': 'Tr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Tre', 'deskripsi': 'Aksara Murda Ta disandhangkan cekre', 'aksara': None, 'terjemahan': 'Tre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Tru', 'deskripsi': 'Aksara Murda Ta disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Tru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Tu', 'deskripsi': 'Aksara Murda Ta disandhangkan suku', 'aksara': None, 'terjemahan': 'Tu', 'alternatif': None, 'let0ak': ['tengah']},
    {'class_code': 'Tw', 'deskripsi': 'Aksara Murda Ta dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'Tw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Twr', 'deskripsi': 'Aksara Murda Ta dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'Twr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Twre', 'deskripsi': 'Aksara Murda Ta dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'Twre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Twru', 'deskripsi': 'Aksara Murda Ta dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Twru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Twu', 'deskripsi': 'Aksara Murda Ta dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'Twu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Ty', 'deskripsi': 'Aksara Murda Ta disandhangkan pengkal', 'aksara': None, 'terjemahan': 'Ty', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'Tyu', 'deskripsi': 'Aksara Murda Ta disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'Tyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'U', 'deskripsi': 'Aksara Swara U', 'aksara': None, 'terjemahan': 'U', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_P', 'deskripsi': 'Aksara Murda Pasangan Pa', 'aksara': None, 'terjemahan': 'P', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_Pr', 'deskripsi': 'Aksara Murda Pasangan Pa disandhangkan cakra', 'aksara': None, 'terjemahan': 'Pr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_Pre', 'deskripsi': 'Aksara Murda Pasangan Pa disandhangkan cekre', 'aksara': None, 'terjemahan': 'Pre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_Pru', 'deskripsi': 'Aksara Murda Pasangan Pa disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Pru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_Pu', 'deskripsi': 'Aksara Murda Pasangan Pa disandhangkan suku', 'aksara': None, 'terjemahan': 'Pu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_Py', 'deskripsi': 'Aksara Murda Pasangan Pa disandhangkan pengkal', 'aksara': None, 'terjemahan': 'Py', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_Pyu', 'deskripsi': 'Aksara Murda Pasangan Pa disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'Pyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_T', 'deskripsi': 'Aksara Murda Pasangan Ta', 'aksara': None, 'terjemahan': 'T', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_Tr', 'deskripsi': 'Aksara Murda Pasangan Ta disandhangkan cakra', 'aksara': None, 'terjemahan': 'Tr', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_Tre', 'deskripsi': 'Aksara Murda Pasangan Ta dsandhangkan cekre', 'aksara': None, 'terjemahan': 'Tre', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_Tru', 'deskripsi': 'Aksara Murda Pasangan Ta disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'Tru', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_Tu', 'deskripsi': 'Aksara Murda Pasangan Ta disandhangkan suku', 'aksara': None, 'terjemahan': 'Tu', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_b', 'deskripsi': 'Aksara Carakan Pasangan ba', 'aksara': None, 'terjemahan': 'b', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_br', 'deskripsi': 'Aksara Carakan Pasangan ba disandhangkan cakra', 'aksara': None, 'terjemahan': 'br', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_bre', 'deskripsi': 'Aksara Carakan Pasangan ba disandhangkan cekre', 'aksara': None, 'terjemahan': 'bre', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_bru', 'deskripsi': 'Aksara Carakan Pasangan ba disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'bru', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_bu', 'deskripsi': 'Aksara Carakan Pasangan ba disandhangkan suku', 'aksara': None, 'terjemahan': 'bu', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_c', 'deskripsi': 'Aksara Carakan Pasangan ca', 'aksara': None, 'terjemahan': 'c', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_cr', 'deskripsi': 'Aksara Carakan Pasangan ca disandhangkan cakra', 'aksara': None, 'terjemahan': 'cr', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_cre', 'deskripsi': 'Aksara Carakan Pasangan ca disandhangkan cekre', 'aksara': None, 'terjemahan': 'cre', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_cru', 'deskripsi': 'Aksara Carakan Pasangan ca disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'cru', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_cu', 'deskripsi': 'Aksara Carakan Pasangan ca disandhangkan suku', 'aksara': None, 'terjemahan': 'cu', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_d', 'deskripsi': 'Aksara Carakan Pasangan da', 'aksara': None, 'terjemahan': 'd', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_dh', 'deskripsi': 'Aksara Carakan Pasangan dha', 'aksara': None, 'terjemahan': 'dh', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_dhr', 'deskripsi': 'Aksara Carakan Pasangan dha disandhangkan cakra', 'aksara': None, 'terjemahan': 'dhr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_dhre', 'deskripsi': 'Aksara Carakan Pasangan dha disandhangkan cekre', 'aksara': None, 'terjemahan': 'dhre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_dhru', 'deskripsi': 'Aksara Carakan Pasangan dha disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'dhru', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_dhu', 'deskripsi': 'Aksara Carakan Pasangan dha disandhangkan suku', 'aksara': None, 'terjemahan': 'dhu', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_dr', 'deskripsi': 'Aksara Carakan Pasangan da disandhangkan cakra', 'aksara': None, 'terjemahan': 'dr', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_dre', 'deskripsi': 'Aksara Carakan Pasangan da disandhangkan cekre', 'aksara': None, 'terjemahan': 'dre', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_dru', 'deskripsi': 'Aksara Carakan Pasangan da disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'dru', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_du', 'deskripsi': 'Aksara Carakan Pasangan da disandhangkan suku', 'aksara': None, 'terjemahan': 'du', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_h', 'deskripsi': 'Aksara Carakan Pasangan ha', 'aksara': None, 'terjemahan': 'h', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_h1', 'deskripsi': 'Sandangan Wignyan h', 'aksara': None, 'terjemahan': 'h', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_hr', 'deskripsi': 'Aksara Carakan Pasangan ha disandhangkan cakra', 'aksara': None, 'terjemahan': 'hr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_hre', 'deskripsi': 'Aksara Carakan Pasangan ha disandhangkan cekre', 'aksara': None, 'terjemahan': 'hre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_hru', 'deskripsi': 'Aksara Carakan Pasangan ha disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'hru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_hu', 'deskripsi': 'Aksara Carakan Pasangan ha disandhangkan suku', 'aksara': None, 'terjemahan': 'hu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_hy', 'deskripsi': 'Aksara Carakan Pasangan ha disandhangkan pengkal', 'aksara': None, 'terjemahan': 'hy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_hyu', 'deskripsi': 'Aksara Carakan Pasangan ha disandhangkan pongkal + suku', 'aksara': None, 'terjemahan': 'hyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_j', 'deskripsi': 'Aksara Carakan Pasangan ja', 'aksara': None, 'terjemahan': 'j', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_jr', 'deskripsi': 'Aksara Carakan Pasangan ja disandhangkan cakra', 'aksara': None, 'terjemahan': 'jr', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_jre', 'deskripsi': 'Aksara Carakan Pasangan ja disandhangkan cekre', 'aksara': None, 'terjemahan': 'jre', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_jru', 'deskripsi': 'Aksara Carakan Pasangan ja disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'jru', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_ju', 'deskripsi': 'Aksara Carakan Pasangan ja disandhangkan suku', 'aksara': None, 'terjemahan': 'ju', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_k', 'deskripsi': 'Aksara Carakan Pasangan ka', 'aksara': None, 'terjemahan': 'k', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_l', 'deskripsi': 'Aksara Carakan Pasangan la', 'aksara': None, 'terjemahan': 'l', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_m', 'deskripsi': 'Aksara Carakan Pasangan ma', 'aksara': None, 'terjemahan': 'm', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_mr', 'deskripsi': 'Aksara Carakan Pasangan ma disandhangkan cakra', 'aksara': None, 'terjemahan': 'mr', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_mre', 'deskripsi': 'Aksara Carakan Pasangan ma disandhangkan cekre', 'aksara': None, 'terjemahan': 'mre', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_mru', 'deskripsi': 'Aksara Carakan Pasangan ma disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'mru', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_mu', 'deskripsi': 'Aksara Carakan Pasangan ma disandhangkan suku', 'aksara': None, 'terjemahan': 'mu', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_p', 'deskripsi': 'Aksara Carakan Pasangan pa', 'aksara': None, 'terjemahan': 'p', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_pr', 'deskripsi': 'Aksara Carakan Pasangan pa disandhangkan cakra', 'aksara': None, 'terjemahan': 'pr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_pre', 'deskripsi': 'Aksara Carakan Pasangan pa disandhangkan cekre', 'aksara': None, 'terjemahan': 'pre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_pru', 'deskripsi': 'Aksara Carakan Pasangan pa disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'pru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_pu', 'deskripsi': 'Aksara Carakan Pasangan pa disandhangkan suku', 'aksara': None, 'terjemahan': 'pu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_py', 'deskripsi': 'Aksara Carakan Pasangan pa disandhgangkan pengkal', 'aksara': None, 'terjemahan': 'py', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_pyu', 'deskripsi': 'Aksara Carakan Pasangan pa disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': '_pyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_r', 'deskripsi': 'Aksara Carakan Pasangan ra', 'aksara': None, 'terjemahan': 'r', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_r1', 'deskripsi': 'Sandhangan Layar r', 'aksara': None, 'terjemahan': 'r', 'alternatif': None, 'letak': ['atas']},
    {'class_code': '_s', 'deskripsi': 'Aksara Carakan Pasangan sa', 'aksara': None, 'terjemahan': 's', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_sr', 'deskripsi': 'Aksara Carakan Pasangan sa disandhangkan cakra', 'aksara': None, 'terjemahan': 'sr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_sre', 'deskripsi': 'Aksara Carakan Pasangan sa disandhangkan cekre', 'aksara': None, 'terjemahan': 'sre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_sru', 'deskripsi': 'Aksara Carakan Pasangan sa disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'sru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_su', 'deskripsi': 'Aksara Carakan Pasangan sa disandhangkan suku', 'aksara': None, 'terjemahan': 'su', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_sy', 'deskripsi': 'Aksara Carakan Pasangan sa disandhangkan pengkal', 'aksara': None, 'terjemahan': 'sy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_syu', 'deskripsi': 'Aksara Carakan Pasangan sa disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'syu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': '_t', 'deskripsi': 'Askara Carakan Pasangan ta', 'aksara': None, 'terjemahan': 't', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_th', 'deskripsi': 'Aksara Carakan Pasangan tha', 'aksara': None, 'terjemahan': 'th', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_thr', 'deskripsi': 'Aksara Carakan Pasangan tha disandhangkan cakra', 'aksara': None, 'terjemahan': 'thr', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_thre', 'deskripsi': 'Aksara Carakan Pasangan tha disandhangkan cekre', 'aksara': None, 'terjemahan': 'thre', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_thru', 'deskripsi': 'Aksara Carakan Pasangan tha disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'thru', 'alternatif': None, 'letak': ['bawah']},
    {'class_code': '_thu', 'deskripsi': 'Aksara Carakan Pasangan tha disandhangkan suku', 'aksara': None, 'terjemahan': 'thu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'adeg2', 'deskripsi': 'Sandhangan Adeg-Adeg', 'aksara': None, 'terjemahan': '||', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'alt', 'deskripsi': 'Sandhangan untuk Aksara Rekan', 'aksara': None, 'terjemahan': None, 'alternatif': None, 'letak': ['atas']},
    {'class_code': 'apit', 'deskripsi': 'Sandhangan Pada Langsa', 'aksara': None, 'terjemahan': None, 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'b', 'deskripsi': 'Aksara Carakan ba', 'aksara': None, 'terjemahan': 'b', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'bn', 'deskripsi': 'Aksara Carakan ba dipasangkan aksara na', 'aksara': None, 'terjemahan': 'bn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'bnu', 'deskripsi': 'Aksara Carakan ba dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'bnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'bny', 'deskripsi': 'Aksara Carakan ba dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'bny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'bnyu', 'deskripsi': 'Aksara Carakan ba dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'bnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'br', 'deskripsi': 'Aksara Carakan ba disandhangkan cakra', 'aksara': None, 'terjemahan': 'br', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'bre', 'deskripsi': 'Aksara Carakan ba disandhangkan cekre', 'aksara': None, 'terjemahan': 'bre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'bru', 'deskripsi': 'Aksara Carakan ba disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'bru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'bu', 'deskripsi': 'Aksara Carakan ba disandhangkan suku', 'aksara': None, 'terjemahan': 'bu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'bw', 'deskripsi': 'Aksara Carakan ba dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'bw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'bwr', 'deskripsi': 'Aksara Carakan ba dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'bwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'bwre', 'deskripsi': 'Aksara Carakan ba dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'bwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'bwru', 'deskripsi': 'Aksara Carakan ba dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'bwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'bwu', 'deskripsi': 'Aksara Carakan ba dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'bwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'bwy', 'deskripsi': 'Aksara Carakan ba dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'bwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'bwyu', 'deskripsi': 'Aksara Carakan ba dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'bwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'by', 'deskripsi': 'Aksara Carakan ba disandhangkan pengkal', 'aksara': None, 'terjemahan': 'by', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'byu', 'deskripsi': 'Aksara Carakan ba disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'byu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'c', 'deskripsi': 'Aksara Carakan ca', 'aksara': None, 'terjemahan': 'c', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cn', 'deskripsi': 'Aksara Carakan ca dipasangkan aksara na', 'aksara': None, 'terjemahan': 'cn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cnu', 'deskripsi': 'Aksara Carakan ca dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'cnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cny', 'deskripsi': 'Aksara Carakan ca dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'cny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cnyu', 'deskripsi': 'Aksara Carakan ca dipasangkan aksara  nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'cnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cr', 'deskripsi': 'Aksara Carakan ca disandhangkan cakra', 'aksara': None, 'terjemahan': 'cr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cre', 'deskripsi': 'Aksara Carakan ca disandhangkan cekre', 'aksara': None, 'terjemahan': 'cre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cru', 'deskripsi': 'Aksara Carakan ca disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'cru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cu', 'deskripsi': 'Aksara Carakan ca disandhangkan suku', 'aksara': None, 'terjemahan': 'cu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cw', 'deskripsi': 'Aksara Carakan ca dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'cw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cwr', 'deskripsi': 'Aksara Carakan ca dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'cwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cwre', 'deskripsi': 'Aksara Carakan ca dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'cwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cwru', 'deskripsi': 'Aksara Carakan ca dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'cwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cwu', 'deskripsi': 'Aksara Carakan ca dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'cwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cwy', 'deskripsi': 'Aksara Carakan ca dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'cwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cwyu', 'deskripsi': 'Aksara Carakan ca dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'cwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cy', 'deskripsi': 'Aksara Carakan ca disandhangkan pengkal', 'aksara': None, 'terjemahan': 'cy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'cyu', 'deskripsi': 'Aksara Carakan ca disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'cyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'd', 'deskripsi': 'Aksara Carakan da', 'aksara': None, 'terjemahan': 'd', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dh', 'deskripsi': 'Aksara Carakan dha', 'aksara': None, 'terjemahan': 'dh', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhn', 'deskripsi': 'Aksara Carakan dha dipasangkan aksara na', 'aksara': None, 'terjemahan': 'dhn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhnu', 'deskripsi': 'Aksara Carakan dha dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'dhnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhny', 'deskripsi': 'Aksara Carakan dha dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'dhny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhnyu', 'deskripsi': 'Aksara Carakan dha dipasangkan aksara nya disandhangkan suku', 'aksara': None, 'terjemahan': 'dhnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhr', 'deskripsi': 'Aksara Carakan dha disandhangkan cakra', 'aksara': None, 'terjemahan': 'dhr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhre', 'deskripsi': 'Aksara Carakan dha disandhangkan cekre', 'aksara': None, 'terjemahan': 'dhre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhru', 'deskripsi': 'Aksara Carakan dha disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'dhru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhu', 'deskripsi': 'Aksara Carakan dha disandhanghkan suku', 'aksara': None, 'terjemahan': 'dhu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhw', 'deskripsi': 'Aksara Carakan dha dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'dhw', 'alternatif': None, 'letak': ['tengah']},    {'class_code': 'dhwr', 'deskripsi': 'Aksara Carakan dha dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'dhwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhwre', 'deskripsi': 'Aksara Carakan dha dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'dhwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhwru', 'deskripsi': 'Aksara Carakahn dha dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'dhwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhwu', 'deskripsi': 'Aksara Carakan dha dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'dhwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhwy', 'deskripsi': 'Aksara Carakan dha dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'dhwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhwyu', 'deskripsi': 'Aksara Carakan dha dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'dhwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhy', 'deskripsi': 'Aksara Carakan dha disandhangkan pengkal', 'aksara': None, 'terjemahan': 'dhy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dhyu', 'deskripsi': 'Aksara Carakan dha disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'dhyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dn', 'deskripsi': 'Aksara Carakan da dipasangkan na', 'aksara': None, 'terjemahan': 'dn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dnu', 'deskripsi': 'Aksara Carakan da dipasangkan na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'dnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dny', 'deskripsi': 'Aksara Carakan da dipasangkan nya', 'aksara': None, 'terjemahan': 'dny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dnyu', 'deskripsi': 'Aksara Carakan da dipasangkan nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'dnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dr', 'deskripsi': 'Aksara Carakan da disandhangkan cakra', 'aksara': None, 'terjemahan': 'dr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dre', 'deskripsi': 'Aksara Carakan da disandhangkan cekre', 'aksara': None, 'terjemahan': 'dre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dru', 'deskripsi': 'Aksara Carakan da disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'dru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'du', 'deskripsi': 'Aksara Carakan da disandhangkan suku', 'aksara': None, 'terjemahan': 'du', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dw', 'deskripsi': 'Aksara Carakan da dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'dw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dwr', 'deskripsi': 'Aksara Carakan da dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'dwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dwre', 'deskripsi': 'Aksara Carakan da dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'dwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dwru', 'deskripsi': 'Aksara Carakan da dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'dwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dwu', 'deskripsi': 'Aksara Carakan da dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'dwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dwy', 'deskripsi': 'Aksara Carakan da dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'dwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dwyu', 'deskripsi': 'Askara Carakan da dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'dwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dy', 'deskripsi': 'Aksara Carakan da disandhangkan pengkal', 'aksara': None, 'terjemahan': 'dy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'dyu', 'deskripsi': 'Aksara Carakan da disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'dyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'e', 'deskripsi': 'Sandhangan Pepet', 'aksara': None, 'terjemahan': 'e', 'alternatif': None, 'letak': ['atas']},
    {'class_code': 'e1', 'deskripsi': 'Sandhangan Taling', 'aksara': None, 'terjemahan': 'e', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ealt', 'deskripsi': 'Sandhangan Pepet + Rekan', 'aksara': None, 'terjemahan': None, 'alternatif': None, 'letak': ['atas']},
    {'class_code': 'eng', 'deskripsi': 'Sandhangan Pepet + Cecek', 'aksara': None, 'terjemahan': 'eng', 'alternatif': None, 'letak': ['atas']},
    {'class_code': 'g', 'deskripsi': 'Aksara Carakan ga', 'aksara': None, 'terjemahan': 'g', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'gn', 'deskripsi': 'Aksara Carakan ga dipasangkan aksara na', 'aksara': None, 'terjemahan': 'gn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'gnu', 'deskripsi': 'Aksara Carakan ga dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'gnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'gny', 'deskripsi': 'Aksara Carakan ga dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'gny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'gnyu', 'deskripsi': 'Aksara Carakan ga dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'gnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'gr', 'deskripsi': 'Aksara Carakan ga disandhangkan cakra', 'aksara': None, 'terjemahan': 'gr', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'gre', 'deskripsi': 'Aksara Carakan ga disandhangkan cekre', 'aksara': None, 'terjemahan': 'gre', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'gru', 'deskripsi': 'Aksara Carakan ga disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'gru', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'gu', 'deskripsi': 'Aksara Carakan ga disandhangkan suku', 'aksara': None, 'terjemahan': 'gu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'gw', 'deskripsi': 'Aksara Carakan ga dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'gw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'gwr', 'deskripsi': 'Aksara Carakan ga dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'gwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'gwre', 'deskripsi': 'Aksara Carakan ga dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'gwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'gwru', 'deskripsi': 'Aksara Carakan ga dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'gwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'gwu', 'deskripsi': 'Aksara Carakan ga dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'gwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'gwy', 'deskripsi': 'Aksara Carakan ga dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'gwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'gwyu', 'deskripsi': 'Aksara Carakan ga dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'gwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'gy', 'deskripsi': 'Aksara Carakan ga disandhangkan pengkal', 'aksara': None, 'terjemahan': 'gy', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'gyu', 'deskripsi': 'Aksara Carakan ga disandhangkan pengka + suku', 'aksara': None, 'terjemahan': 'gyu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'h', 'deskripsi': 'Aksara Carakan ha', 'aksara': None, 'terjemahan': 'h', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hn', 'deskripsi': 'Aksara Carakan ha dipasangkan aksara na', 'aksara': None, 'terjemahan': 'hn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hnu', 'deskripsi': 'Aksara Carakan ha dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'hnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hny', 'deskripsi': 'Aksara Carakan ha dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'hny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hnyu', 'deskripsi': 'Aksara Carakan ha dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'hnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hr', 'deskripsi': 'Aksara Carakan ha disandhangkan cakra', 'aksara': None, 'terjemahan': 'hr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hre', 'deskripsi': 'Aksara Carakan ha disandhangkan cekre', 'aksara': None, 'terjemahan': 'hre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hru', 'deskripsi': 'Aksara Carakan ha disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'hru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hu', 'deskripsi': 'Aksara Carakan ha disandhangkan suku', 'aksara': None, 'terjemahan': 'hu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hw', 'deskripsi': 'Aksara Carakan ha dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'hw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hwr', 'deskripsi': 'Aksara Carakan ha dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'hwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hwre', 'deskripsi': 'Aksara Carakan ha dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'hwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hwru', 'deskripsi': 'Aksara Carakan ha dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'hwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hwu', 'deskripsi': 'Aksara Carakan ha dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'hwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hwy', 'deskripsi': 'Aksara Carakan ha dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'hwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hwyu', 'deskripsi': 'Aksara Carakan ha dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'hwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hy', 'deskripsi': 'Aksara Carakan ha disandhangkan pengkal', 'aksara': None, 'terjemahan': 'hy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'hyu', 'deskripsi': 'Aksara Carakan ha disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'hyu','alternatif': None, 'letak': ['tengah']},
    {'class_code': 'i', 'deskripsi': 'Sandhangan Wulu', 'aksara': None, 'terjemahan': 'i', 'alternatif': None, 'letak': ['atas']},
    {'class_code': 'j', 'deskripsi': 'Aksara Carakan ja', 'aksara': None, 'terjemahan': 'j', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jn', 'deskripsi': 'Aksara Carakan ja dipasangkan aksara na', 'aksara': None, 'terjemahan': 'jn', 'alternatif': None, 'letak': [['tengah']]},
    {'class_code': 'jnu', 'deskripsi': 'Aksara Carakan ja dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'jnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jny', 'deskripsi': 'Aksara Carakan ja dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'jny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jnyu', 'deskripsi': 'Aksara Carakan ja dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'jnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jr', 'deskripsi': 'Aksara Carakan ja disandhangkan cakra', 'aksara': None, 'terjemahan': 'jr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jre', 'deskripsi': 'Aksara Carakan ja disandhangkan cekre', 'aksara': None, 'terjemahan': 'jre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jru', 'deskripsi': 'Aksara Carakan ja disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'jru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ju', 'deskripsi': 'Aksara Carakan ja disandhangkan suku', 'aksara': None, 'terjemahan': 'ju', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jw', 'deskripsi': 'Aksara Carakan ja dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'jw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jwr', 'deskripsi': 'Aksara Carakan ja dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'jwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jwre', 'deskripsi': 'Aksara Carakan ja dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'jwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jwru', 'deskripsi': 'Aksara Carakan ja dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'jwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jwu', 'deskripsi': 'Aksara Carakan ja dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'jwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jwy', 'deskripsi': 'Aksara Carakan ja dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'jwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jwyu', 'deskripsi': 'Aksara Carakan ja dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'jwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jy', 'deskripsi': 'Aksara Carakan ja disandhangkan pengkal', 'aksara': None, 'terjemahan': 'jy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'jyu', 'deskripsi': 'Aksara Carakan ja disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'jyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'k', 'deskripsi': 'Aksara Carakan ka', 'aksara': None, 'terjemahan': 'k', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'kn', 'deskripsi': 'Aksara Carakan ka dipasangkan aksara na', 'aksara': None, 'terjemahan': 'kn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'knu', 'deskripsi': 'Aksara Carakan ka dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'knu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'kny', 'deskripsi': 'Aksara Carakan ka dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'kny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'knyu', 'deskripsi': 'Aksara Carakan ka dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'knyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'kom', 'deskripsi': 'Sandhangan Pada Lingsang', 'aksara': None, 'terjemahan': ',', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'kr', 'deskripsi': 'Aksara Carakan ka disandhangkan cakra', 'aksara': None, 'terjemahan': 'kr', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'kre', 'deskripsi': 'Aksara Carakan ka disandhangkan cekre', 'aksara': None, 'terjemahan': 'kre', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'kru', 'deskripsi': 'Aksara Carakan ka disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'kru', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'ku', 'deskripsi': 'Aksara Carakan ka disandhangkan suku', 'aksara': None, 'terjemahan': 'ku', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'kw', 'deskripsi': 'Aksara Carakan ka dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'kw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'kwr', 'deskripsi': 'Aksara Carakan ka dipasangakan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'kwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'kwre', 'deskripsi': 'Aksara Carakan ka dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'kwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'kwru', 'deskripsi': 'Aksara Carakan ka dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'kwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'kwu', 'deskripsi': 'Aksara Carakan ka dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'kwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'kwy', 'deskripsi': 'Aksara Carakan ka dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'kwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'kwyu', 'deskripsi': 'Aksara Carakan ka dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'kwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ky', 'deskripsi': 'Aksara Carakan ka disandhangkan pengkal', 'aksara': None, 'terjemahan': 'ky', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'kyu', 'deskripsi': 'Aksara Carakan ka disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'kyu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'l', 'deskripsi': 'Aksara Carakan la', 'aksara': None, 'terjemahan': 'l', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ln', 'deskripsi': 'Aksara Carakan la dipasangkan aksara na', 'aksara': None, 'terjemahan': 'ln', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'lnu', 'deskripsi': 'Aksara Carakan la dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'lnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'lny', 'deskripsi': 'Aksara Carakan la dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'lny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'lnyu', 'deskripsi': 'Aksara Carakan la dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'lnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'lr', 'deskripsi': 'Aksara Carakan la disandhangkan cakra', 'aksara': None, 'terjemahan': 'lr', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'lre', 'deskripsi': 'Aksara Carakan la disandhangkan cekre', 'aksara': None, 'terjemahan': 'lre', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'lru', 'deskripsi': 'Aksara Carakan la disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'lru', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'lu', 'deskripsi': 'Aksara Carakan la disandhangkan suku', 'aksara': None, 'terjemahan': 'lu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'lw', 'deskripsi': 'Aksara Carakan la dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'lw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'lwr', 'deskripsi': 'Aksara Carakan la dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'lwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'lwre', 'deskripsi': 'Aksara Carakan la dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'lwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'lwru', 'deskripsi': 'Aksara Carakan la dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'lwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'lwu', 'deskripsi': 'Aksara Carakan la dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'lwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'lwy', 'deskripsi': 'Aksara Carakan la dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'lwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'lwyu', 'deskripsi': 'Aksara Carakan la dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'lwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ly', 'deskripsi': 'Aksara Carakan la disandhangkan pengkal', 'aksara': None, 'terjemahan': 'ly', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'lyu', 'deskripsi': 'Aksara Carakan la disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'lyu', 'alternatif': None, 'letak': ['tengah', ' bawah']},
    {'class_code': 'm', 'deskripsi': 'Aksara Carakan ma', 'aksara': None, 'terjemahan': 'm', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mn', 'deskripsi': 'Aksara Carakan ma dipasangkan na', 'aksara': None, 'terjemahan': 'mn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mnu', 'deskripsi': 'Aksara Carakan ma dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'mnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mny', 'deskripsi': 'Aksara Carakan ma dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'mny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mnyu', 'deskripsi': 'Aksara Carakan ma dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'mnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mr', 'deskripsi': 'Aksara Carakan ma disandhangkan cakra', 'aksara': None, 'terjemahan': 'mr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mre', 'deskripsi': 'Aksara Carakan ma disandhangkan cekre', 'aksara': None, 'terjemahan': 'mre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mru', 'deskripsi': 'Aksara Carakan ma disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'mru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mu', 'deskripsi': 'Aksara Carakan ma disandhangkan suku', 'aksara': None, 'terjemahan': 'mu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mw', 'deskripsi': 'Aksara Carakan ma dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'mw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mwr', 'deskripsi': 'Aksara Carakan ma dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'mwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mwre', 'deskripsi': 'Aksara Carakan ma dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'mwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mwru', 'deskripsi': 'Aksara Carakan ma dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'mwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mwu', 'deskripsi': 'Aksara Carakan ma dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'mwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mwy', 'deskripsi': 'Aksara Carakan ma dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'mwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'mwyu', 'deskripsi': 'Aksara Carakan ma dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'mwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'my', 'deskripsi': 'Aksara Carakan ma disandhangkan pengkal', 'aksara': None, 'terjemahan': 'my', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'myu', 'deskripsi': 'Aksara Carakan ma disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'myu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'n', 'deskripsi': 'Aksara Carakan na', 'aksara': None, 'terjemahan': 'n', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ng', 'deskripsi': 'Sandhangan Cecek ng', 'aksara': None, 'terjemahan': 'ng', 'alternatif': None, 'letak': ['atas']},
    {'class_code': 'nga', 'deskripsi': 'Aksara Carakan nga', 'aksara': None, 'terjemahan': 'ng', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'ngna', 'deskripsi': 'Aksara Carakan nga dipasangkan aksara na', 'aksara': None, 'terjemahan': 'ngn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ngnu', 'deskripsi': 'Aksara Carakan nga dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'ngnu', 'alternatif': None,  'letak': ['tengah']},
    {'class_code': 'ngnya', 'deskripsi': 'Aksara Carakan nga dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'ngny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ngnyu', 'deskripsi': 'Aksara Carakan nga dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'ngnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ngra', 'deskripsi': 'Aksara Carakan nga disandhangkan cakra', 'aksara': None, 'terjemahan': 'ngr', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'ngre', 'deskripsi': 'Aksara Carakan nga disandhangkan cekre', 'aksara': None, 'terjemahan': 'ngre', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'ngru', 'deskripsi': 'Aksara Carakan nga disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'ngru', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'ngu', 'deskripsi': 'Aksara Carakan nga disandhangkan suku', 'aksara': None, 'terjemahan': 'ngu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'ngwa', 'deskripsi': 'Aksara Carakan nga dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'ngw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ngwra', 'deskripsi': 'Aksara Carakan nga dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'ngwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ngwre', 'deskripsi': 'Aksara Carakan nga dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'ngwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ngwru', 'deskripsi': 'Aksara Carakan nga dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'ngwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ngwu', 'deskripsi': 'Aksara Carakan nga dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'ngwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ngwya', 'deskripsi': 'Aksara Carakan nga dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'ngwy',  'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ngwyu', 'deskripsi': 'Aksara Carakan nga dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'ngwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ngya', 'deskripsi': 'Aksara Carakan nga disandhangkan pengkal', 'aksara': None, 'terjemahan': 'ngy', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'ngyu', 'deskripsi': 'Aksara Carakan nga disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'ngyu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'nn', 'deskripsi': 'Aksara Carakan na dipasangkan aksara na', 'aksara': None, 'terjemahan': 'nn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nnu', 'deskripsi': 'Aksara Carakan na dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'nnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nny', 'deskripsi': 'Aksara Carakan na dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'nny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nnyu', 'deskripsi': 'Aksara Carakan na dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'nnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nr', 'deskripsi': 'Aksara Carakan na disandhangkan cakra', 'aksara': None, 'terjemahan': 'nr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nre', 'deskripsi': 'Aksara Carakan na disandhangkan cekre', 'aksara': None, 'terjemahan': 'nre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nru', 'deskripsi': 'Aksara Carakan na disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'nru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nu', 'deskripsi': 'Aksara Carakan na disandhangkan suku', 'aksara': None, 'terjemahan': 'nu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nw', 'deskripsi': 'Aksara Carakan na dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'nw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nwr', 'deskripsi': 'Aksara Carakan na dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'nwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nwre', 'deskripsi': 'Aksara Carakan na dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'nwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nwru', 'deskripsi': 'Aksara Carakan na dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'nwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nwu', 'deskripsi': 'Aksara Carakan na dipasangkan aksara wa dan dfisandhangkan suku', 'aksara': None, 'terjemahan': 'nwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nwy', 'deskripsi': 'Aksara Carakan na dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'nwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nwyu', 'deskripsi': 'Aksara Carakan na dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'nwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ny', 'deskripsi': 'Aksara Carakan na disandhangkan pengkal', 'aksara': None, 'terjemahan': 'ny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ny1', 'deskripsi': 'Aksara Carakan nya', 'aksara': None, 'terjemahan': 'ny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nyn', 'deskripsi': 'Aksara Carakan nya dipasangkan aksara na', 'aksara': None, 'terjemahan': 'nyn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nynu', 'deskripsi': 'Aksara Carakan nya dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'nynu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nyny', 'deskripsi': 'Aksara Carakan nya dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'nyny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nynyu', 'deskripsi': 'Aksara Carakan nya dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'nynyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nyr', 'deskripsi': 'Aksara Carakan nya disandhangkan cakra', 'aksara': None, 'terjemahan': 'nyr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nyre', 'deskripsi': 'Aksara Carakan nya disandhangkan cekre', 'aksara': None, 'terjemahan': 'nyre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nyru', 'deskripsi': 'Aksara Carakan nya disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'nyru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nyu', 'deskripsi': 'Aksara Carakan na disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'nyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nyu1', 'deskripsi': 'Aksara Carakan nya disandhangkan suku', 'aksara': None, 'terjemahan': 'nyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nyw', 'deskripsi': 'Aksara Carakan nya dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'nyw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nywr', 'deskripsi': 'Aksara Carakan nya dipasnagkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'nywr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nywre', 'deskripsi': 'Aksara Carakan nya dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'nywre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nywru', 'deskripsi': 'Aksara Carakan nya dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'nywru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nywu', 'deskripsi': 'Aksara Carakan nya dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'nywu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nywy', 'deskripsi': 'Aksara Carakan nya dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'nywy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nywyu', 'deskripsi': 'Aksara Carakan nya dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'nywyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nyy', 'deskripsi': 'Aksara Carakan nya disandhangkan pengkal', 'aksara': None, 'terjemahan': 'nyy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'nyyu', 'deskripsi': 'Aksara Carakan nya disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'nyyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'o', 'deskripsi': 'Sandhangan Taling Talung', 'aksara': None, 'terjemahan': 'o', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'p', 'deskripsi': 'Aksara Carakan pa', 'aksara': None, 'terjemahan': 'p', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pn', 'deskripsi': 'Aksara Carakan pa dipasangkan aksara na', 'aksara': None, 'terjemahan': 'pn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pnu', 'deskripsi': 'Aksara Carakan pa dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'pnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pny', 'deskripsi': 'Aksara Carakan pa dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'pny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pnyu', 'deskripsi': 'Aksara Carakan pa dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'pnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pr', 'deskripsi': 'Aksara Carakan pa disandhangkan cakra','aksara': None, 'terjemahan': 'pr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pre', 'deskripsi': 'Aksara Carakan pa disandhangkan cekre', 'aksara': None, 'terjemahan': 'pre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pru', 'deskripsi': 'Aksara Carakan pa disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'pru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pu', 'deskripsi': 'Aksara Carakan pa disandhangkan suku', 'aksara': None, 'terjemahan': 'pu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pw', 'deskripsi': 'Aksara Carakan pa dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'pw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pwr', 'deskripsi': 'Aksara Carakan pa dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'pwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pwre', 'deskripsi': 'Aksara Carakan pa dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'pwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pwru', 'deskripsi': 'Aksara Carakan pa dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'pwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pwu', 'deskripsi': 'Aksara Carakan pa dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'pwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pwy', 'deskripsi': 'Aksara Carakan pa dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'pwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pwyu', 'deskripsi': 'Aksara Carakan pa dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'pwyu', 'alternatif': None, 'letak': 'tengah'},
    {'class_code': 'py', 'deskripsi': 'Aksara Carakan pa disandhangkan pengkal', 'aksara': None, 'terjemahan': 'py', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'pyu', 'deskripsi': 'Aksara Carakan pa disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'pyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'r', 'deskripsi': 'Aksara Carakan ra', 'aksara': None, 'terjemahan': 'r', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'rn', 'deskripsi': 'Aksara Carakan ra dipasangkan na', 'aksara': None, 'terjemahan': 'rn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'rnu', 'deskripsi': 'Aksara Carakan ra dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'rnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'rny', 'deskripsi': 'Aksara Carakan ra dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'rny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'rnyu', 'deskripsi': 'Aksara Carakan ra dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'rnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'rr', 'deskripsi': 'Aksara Carakan ra disandhangkan cakra', 'aksara': None, 'terjemahan': 'rr', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'rre', 'deskripsi': 'Aksara Carakan ra disandhangkan cekre', 'aksara': None, 'terjemahan': 'rre', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'rru', 'deskripsi': 'Aksara Carakan ra disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'rru', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'ru', 'deskripsi': 'Aksara Carakan ra disandhangkan suku', 'aksara': None, 'terjemahan': 'ru', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'rw', 'deskripsi': 'Aksara Carakan ra dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'rw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'rwr', 'deskripsi': 'Aksara Carakan ra dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'rwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'rwre', 'deskripsi': 'Aksara Carakan ra dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'rwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'rwru', 'deskripsi': 'Aksara Carakan ra dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'rwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'rwu', 'deskripsi': 'Aksara Carakan ra dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'rwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'rwy', 'deskripsi': 'Aksara Carakan ra dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'rwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'rwyu', 'deskripsi': 'Aksara Carakan ra dipasangkan aksara wa dan disandangkan pengkal + suku', 'aksara': None, 'terjemahan': 'rwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ry', 'deskripsi': 'Aksara Carakan ra disandhangkan pengkal', 'aksara': None, 'terjemahan': 'ry', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'ryu', 'deskripsi': 'Aksara Carakan ra disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'ryu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 's', 'deskripsi': 'Aksara Carakan sa', 'aksara': None, 'terjemahan': 's', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'sn', 'deskripsi': 'Aksara Carakan sa dipasangkan aksara na', 'aksara': None, 'terjemahan': 'sn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'snu', 'deskripsi': 'Aksara Carakan sa dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'snu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'sny', 'deskripsi': 'Aksara Carakan sa dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'sny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'snyu', 'deskripsi': 'Aksara Carakan sa dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'snyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'sr', 'deskripsi': 'Aksara Carakan sa disandhangkan cakra', 'aksara': None, 'terjemahan': 'sr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'sre', 'deskripsi': 'Aksara Carakan sa disandhangkan cekre', 'aksara': None, 'terjemahan': 'sre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'sru', 'deskripsi': 'Aksara Carakan sa disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'sru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'su', 'deskripsi': 'Aksara Carakan sa disandhangkan suku', 'aksara': None, 'terjemahan': 'su', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'sw', 'deskripsi': 'Aksara Carakan sa dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'sw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'swr', 'deskripsi': 'Aksara Carakan sa dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'swr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'swre', 'deskripsi': 'Aksara Carakan sa dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'swre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'swru', 'deskripsi': 'Aksara Carakan sa dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'swru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'swu', 'deskripsi': 'Aksara Caraka sa dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'swu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'swy', 'deskripsi': 'Aksara Carakan sa dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'swy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'swyu', 'deskripsi': 'Aksara Carakan sa dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'swyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'sy', 'deskripsi': 'Aksara Carakan sa disandhangkan pengkal', 'aksara': None, 'terjemahan': 'sy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'syu', 'deskripsi': 'Aksara Carakan sa disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'syu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 't', 'deskripsi': 'Aksara Carakan ta', 'aksara': None, 'terjemahan': 't', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'th', 'deskripsi': 'Aksara Carakan tha', 'aksara': None, 'terjemahan': 'th', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thn', 'deskripsi': 'Aksara Carakan tha dipasangkan aksara na', 'aksara': None, 'terjemahan': 'thn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thnu', 'deskripsi': 'Aksara Carakan tha dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'thnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thny', 'deskripsi': 'Aksara Carakan tha dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'thny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thnyu', 'deskripsi': 'Aksara Carakan tha dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'thnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thr', 'deskripsi': 'Aksara Carakan tha disandhangkan cakra', 'aksara': None, 'terjemahan': 'thr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thre', 'deskripsi': 'Aksara Carakan tha disandhangkan cekre', 'aksara': None, 'terjemahan': 'thre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thru', 'deskripsi': 'Aksara Carakan tha disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'thru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thu', 'deskripsi': 'Aksara Carakan tha disandhangkan suku', 'aksara': None, 'terjemahan': 'thu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thw', 'deskripsi': 'Aksara Carakan tha dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'thw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thwr', 'deskripsi': 'Aksara Carakan tha dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'thwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thwre', 'deskripsi': 'Aksara Carakan tha dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'thwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thwru', 'deskripsi': 'Aksara Carakan tha dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'thwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thwu', 'deskripsi': 'Aksara Carakan tha dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'thwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thwy', 'deskripsi': 'Aksara Carakan tha dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'thwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thwyu', 'deskripsi': 'Aksara Carakan tha dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'thwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thy', 'deskripsi': 'Aksara Carakan tha disandhangkan pengkal', 'aksara': None, 'terjemahan': 'thy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'thyu', 'deskripsi': 'Aksara Carakan tha disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'thyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'tn', 'deskripsi': 'Aksara Carakan ta dipasangkan aksara na', 'aksara': None, 'terjemahan': 'tn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'tnu', 'deskripsi': 'Aksara Carakan ta dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'tnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'tny', 'deskripsi': 'Aksara Carakan ta dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'tny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'tnyu', 'deskripsi': 'Aksara Carakan ta dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'tnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'tr', 'deskripsi': 'Aksara Carakan ta disandhangkan cakra', 'aksara': None, 'terjemahan': 'tr', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'tre', 'deskripsi': 'Aksara Carakan ta disandhangkan cekre', 'aksara': None, 'terjemahan': 'tre', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'tru', 'deskripsi': 'Aksara Carakan ta disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'tru', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'tu', 'deskripsi': 'Aksara Carakan ta disandhangkan suku', 'aksara': None, 'terjemahan': 'tu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'tw', 'deskripsi': 'Aksara Carakan ta dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'tw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'twr', 'deskripsi': 'Aksara Carakan ta dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'twr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'twre', 'deskripsi': 'Aksara Carakan ta dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'twre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'twru', 'deskripsi': 'Aksara Carakan ta dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'twru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'twu', 'deskripsi': 'Aksara Carakan ta dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'twu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'twy', 'deskripsi': 'Aksara Carakan ta dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'twy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'twyu', 'deskripsi': 'Aksara Carakan ta dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'twyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ty', 'deskripsi': 'Aksara Carakan ta disandhangkan pengkal', 'aksara': None, 'terjemahan': 'ty', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'tyu', 'deskripsi': 'Aksara Carakan ta disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'tyu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'w', 'deskripsi': 'Aksara Carakan wa', 'aksara': None, 'terjemahan': 'w', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wn', 'deskripsi': 'Aksara Carakan wa dipasangkan aksara na', 'aksara': None, 'terjemahan': 'wn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wnu', 'deskripsi': 'Aksara Carakan wa dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'wnu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wny', 'deskripsi': 'Aksara Carakan wa dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'wny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wnyu', 'deskripsi': 'Aksara Carakan wa dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'wnyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wr', 'deskripsi': 'Aksara Carakan wa disandhangkan cakra', 'aksara': None, 'terjemahan': 'wr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wre', 'deskripsi': 'Aksara Carakan wa disandhangkan cekre', 'aksara': None, 'terjemahan': 'wre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wru', 'deskripsi': 'Aksara Carakan wa disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'wru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wu', 'deskripsi': 'Aksara Carakan wa disandhangkan suku', 'aksara': None, 'terjemahan': 'wu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ww', 'deskripsi': 'Aksara Carakan wa dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'ww', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wwr', 'deskripsi': 'Aksara Carakan wa dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'wwr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wwre', 'deskripsi': 'Aksara Carakan wa dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'wwre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wwru', 'deskripsi': 'Aksara Carakan wa dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'wwru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wwu', 'deskripsi': 'Aksara Carakan wa dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'wwu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wwy', 'deskripsi': 'Aksara Carakan wa dipasangkan aksara wa dan  disandhangkan pengkal', 'aksara': None, 'terjemahan': 'wwy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wwyu', 'deskripsi': 'Aksara Carakan wa dipasangkan aksara wa dan disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'wwyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wy', 'deskripsi': 'Aksara Carakan wa disandhangkan pengkal', 'aksara': None, 'terjemahan': 'wy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'wyu', 'deskripsi': 'Aksara Carakan wa disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'wyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'y', 'deskripsi': 'Aksara Carakan ya', 'aksara': None, 'terjemahan': 'y', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'yn', 'deskripsi': 'Aksara Carakan ya dipasangkan aksara na', 'aksara': None, 'terjemahan': 'yn', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ynu', 'deskripsi': 'Aksara Carakan ya dipasangkan aksara na dan disandhangkan suku', 'aksara': None, 'terjemahan': 'ynu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'yny',  'deskripsi': 'Aksara Carakan ya dipasangkan aksara nya', 'aksara': None, 'terjemahan': 'yny', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ynyu', 'deskripsi': 'Aksara Carakan ya dipasangkan aksara nya dan disandhangkan suku', 'aksara': None, 'terjemahan': 'ynyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'yr', 'deskripsi': 'Aksara Carakan ya disandhangkan cakra', 'aksara': None, 'terjemahan': 'yr', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'yre', 'deskripsi': 'Aksara Carakan ya disandhangkan cekre', 'aksara': None, 'terjemahan': 'yre', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'yru', 'deskripsi': 'Aksara Carakan ya disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'yru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'yu', 'deskripsi': 'Aksara Carakan ya disandhangkan suku', 'aksara': None, 'terjemahan': 'yu', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'yw', 'deskripsi': 'Aksara Carakan ya dipasangkan aksara wa', 'aksara': None, 'terjemahan': 'yw', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ywr', 'deskripsi': 'Aksara Carakan ya dipasangkan aksara wa dan disandhangkan cakra', 'aksara': None, 'terjemahan': 'ywr', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ywre', 'deskripsi': 'Aksara Carakan ya dipasangkan aksara wa dan disandhangkan cekre', 'aksara': None, 'terjemahan': 'ywre', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ywru', 'deskripsi': 'Aksara Carakan ya dipasangkan aksara wa dan disandhangkan cakra + suku', 'aksara': None, 'terjemahan': 'ywru', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ywu', 'deskripsi': 'Aksara Carakan ya dipasangkan aksara wa dan disandhangkan suku', 'aksara': None, 'terjemahan': 'ywu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ywy', 'deskripsi': 'Aksara Carakan ya dipasangkan aksara wa dan disandhangkan pengkal', 'aksara': None, 'terjemahan': 'ywy', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'ywyu', 'deskripsi': 'Aksara Carakan ya dipasangkan aksara wa dan disandhangkan pengka + suku', 'aksara': None, 'terjemahan': 'ywyu', 'alternatif': None, 'letak': ['tengah']},
    {'class_code': 'yy', 'deskripsi': 'Aksara Carakan ya disandhangkan pengkal', 'aksara': None, 'terjemahan': 'yy', 'alternatif': None, 'letak': ['tengah', 'bawah']},
    {'class_code': 'yyu', 'deskripsi': 'Aksara Carakan ya disandhangkan pengkal + suku', 'aksara': None, 'terjemahan': 'yyu', 'alternatif': None, 'letak': ['tengah', ' bawah']}]